# Configurações do Servidor
server:
  port: 8080

# Configurações Gerais do Spring
spring:
  # Ativa o perfil de desenvolvimento para que o DatabaseSeeder seja executado
  profiles:
    active: dev

  application:
    name: terrasync-backend

  # Configurações do Banco de Dados (Datasource) - PREENCHER
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-database}:5431/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Configurações do JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    # Configurações para facilitar a depuração (desenvolvimento)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configurações de monitoramento (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        # Expõe os endpoints de 'health' (saúde da aplicação) e 'info'.
        include: health,info

api:
  security:
    token:
      secret: MySecretKeysSuperLongaDePeloMenos64CaracteresBase64CriadoPorMatheusLeão
